name: ballgown
owner: iuc
description: this is a wrapper for the ballgown 2.2.0 package
long_description:
  Ballgown is a software package designed to facilitate flexible differential expression analysis of RNA-seq data.
  The Ballgown package provides functions to organize, visualize, and analyze the expression measurements for your transcriptome assembly.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/ballgown
type: unrestricted
categories:
  - statistics
  - RNA-Seq
